name: PySal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - notebook=5.7
  - pysal=2.0
  - pandas=0.24
  - geopandas=0.4.1
  - contextily=1.0rc1
  - dill=0.2.9
  - ipywidgets=7.4.2
